# Generated by Django 6.0.7 on 2026-07-09 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('material', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG'), ('ABS', 'ABS'), ('TPU', 'TPU'), ('RESIN', 'Resin')], default='PLA', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='custom_orders/files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='custom_orders/images/')),
                ('status', models.CharField(choices=[('new', 'New'), ('review', 'Under Review'), ('quote_sent', 'Quote Sent'), ('accepted', 'Accepted'), ('printing', 'Printing'), ('finished', 'Finished'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
