# Generated by Django 6.0.7 on 2026-07-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='engraving_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='engraving_image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_orders/engraving/'),
        ),
        migrations.AddField(
            model_name='customorder',
            name='engraving_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customorder',
            name='service',
            field=models.CharField(choices=[('printing', '3D Printing'), ('engraving', 'Engraving'), ('printing_engraving', '3D Printing + Engraving')], default='printing', max_length=30),
        ),
    ]
