# Generated by Django 6.0.7 on 2026-07-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0002_customorder_engraving_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='engraving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customorder',
            name='engraving_type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('logo', 'Logo'), ('design', 'Custom Design')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='engraving_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
