# Generated by Django 6.0.7 on 2026-07-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0003_customorder_engraving_customorder_engraving_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='engraving_details',
        ),
        migrations.AlterField(
            model_name='customorder',
            name='engraving_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='engraving_type',
            field=models.CharField(choices=[('none', 'No engraving'), ('text', 'Text engraving'), ('logo', 'Logo engraving'), ('image', 'Image engraving')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='service',
            field=models.CharField(choices=[('printing', '3D Printing'), ('engraving', 'Engraving'), ('both', '3D Printing + Engraving')], default='printing', max_length=20),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('review', 'Under Review'), ('quote_sent', 'Quote Sent'), ('accepted', 'Accepted'), ('printing', 'Production'), ('finished', 'Finished'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
