# Generated by Django 6.0.7 on 2026-07-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0004_remove_customorder_engraving_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='material',
            field=models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG'), ('ABS', 'ABS'), ('TPU', 'TPU')], default='PLA', max_length=20),
        ),
    ]
